### ISSUE TITLE
GB: The Smurfs (USA/EUR) Rev A - Hangs on Nintendo

### ISSUE THREAD

**Issue by Takumoru** [MiSTer-devel/Gameboy_MiSTer#81] opened 2020-06-15 15:35 UTC
The Smurfs on Game Boy doesn’t get past the Nintendo logo (alternatively goes to white, blank screen after system boot with GBC bootrom/bios).

Only tested Rev A since that’s the only version I have available. Asked more people to test on MiSTer FPGA Computer Facebook page and at least one other person confirmed the issue.

**Comment by paulb-nl** [comment] 2020-06-23 09:43
@brNX This seems to be caused by not emulating the HALT bug described here at "4.10. The HALT Instruction Behaviour" https://github.com/AntonioND/giibiiadvance/blob/master/docs/TCAGBD.pdf

if IME = 0 and (IE & IF) != 0 then 
`"HALT mode is not entered. HALT bug occurs: The CPU fails to increase PC when
executing the next instruction. The IF flags aren't cleared. This results on weird
behaviour. "`

There is an halt instruction here where it loops infinitely:
````
$0E3A 76    halt
$0E3B F0 8C  ld a,(ff00+8C)
$0E3D A7     and a
$0E3E 28 FA   jr z,0E3A
````
There is a Vblank IF & IE and that point and IME = 0. According to the bug description this should happen:
````
$0E3A 76    halt
$0E3B F0 F0  ld a,(ff00+F0) <- opcode byte repeated
$0E3C 8C    adc h
$0E3D A7     and a
$0E3E 28 FA   jr z,0E3A
````

BGB does something similar.

**Comment by brNX** [comment] 2020-06-23 12:07
@paulb-nl that one seems trickier to implement, interesting, there's a test rom for that case if I remember right. I'll have a look asap

**Comment by brNX** [comment] 2020-06-25 20:16
@paulb-nl I think I got this one, it was actually easier than I thought, I somehow replicated the repeating byte without trying much , I checked in simulation, will send a PR after checking it with signaltap

![bgbhaltbug](https://user-images.githubusercontent.com/407195/85791014-13166b80-b729-11ea-982f-f8620665c04e.png)

with bug:
![bug](https://user-images.githubusercontent.com/407195/85790894-eb270800-b728-11ea-8a83-aa30abb9df83.png)

without bug:
![withoutbug](https://user-images.githubusercontent.com/407195/85790900-ecf0cb80-b728-11ea-8d4e-2f36a9714527.png)

**Closed** 2020-06-27 14:06 UTC
