### ISSUE TITLE
Perfect Dark (GBC) - No PCM Sound

### ISSUE THREAD

**Issue by flying-banana** [MiSTer-devel/Gameboy_MiSTer#87] opened 2020-06-24 01:24 UTC
In the GBC game Perfect Dark the PCM sound (which plays a relatively big part in this game) does not work.

Steps to reproduce: press start a few times once the game boots in order to select a new game and have the game automatically create a name for your save file. After the name entry screen, an intro dialog screen will appear.  This dialog should be fully voiced via PCM samples, but instead there's silence. Same goes for all the gunshots, footsteps, and various grunts/yells the characters make throughout the game. 

Example video with the PCM samples in the intro playing correctly; relevant section starts at about 54sec: https://youtu.be/xeLNNsVPSCA?t=54

**Comment by mario-64** [comment] 2020-07-03 03:42
I can confirm this issue is present even in the test build containing SGB fixes

**Comment by owlnonymous** [comment] 2020-08-08 02:56
I was just coming to report this. Thanks OP for already submitting the issue.

**Comment by maij** [comment] 2022-10-18 07:32
I have recently been working to fix this (following a few different tracks because I am no expert on the gameboy).

Two observations:
- If I force all channel amplitudes to max, then during the opening credits (the laser cutting the Nintendo symbol and Rare token flying in) the audio sounds correct to me (previously it was muted) 
- When I implemented high-pass filtering on the Square wave channel alone (core: [Gameboy_sq1_ch_hpf.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/9807546/Gameboy_sq1_ch_hpf.zip)) then the PCM voice samples of Daniel and Joanna can be heard, as well as other important features during gameplay (gunshots, footsteps, guards voice sample upon being shot).

The curious thing is that high-pass filtering (AFAIK) is meant to be performed on the post-mixed audio signal, but when I do that I don't get any audio out at all. I'm hoping it's a simple bug. I've been following the implementation of the [https://github.com/LIJI32/SameBoy/blob/cb33119114f9479f41b10e61c5752925d3078864/Core/apu.c#L238](sameboy apu).

**Comment by sorgelig** [comment] 2022-10-18 10:29
> * If I force all channel amplitudes to max, then during the opening credits (the laser cutting the Nintendo symbol and Rare token flying in) the audio sounds correct to me (previously it was muted)

are you talking about initial amplitude setting, or you have to force keep it to max?

**Comment by maij** [comment] 2022-10-18 14:31
For that test I forced the volume of each channel to max, the whole time. I did originally think that maybe the boot.rom was meant to be initialising the APU registers and that wasn't happening, but I have since removed the forced max volume (allowing them to be set/get as intended) and that audio segment is audible when making other changes to the APU. I can confirm what other variants result in this audio segment being heard later.

**Comment by sorgelig** [comment] 2022-10-18 15:56
so game just needs initial volume set to max?

**Comment by maij** [comment] 2022-10-18 21:01
I just tested this (setting the initial values of both volume and "svol" to be "1111"), and it does not fix the issue (no audio during opening sequence).

Based on my tests in Sameboy (removing DAC charging, removing high-pass filtering, removing PCM audio); even without these added components Sameboy still produces something close to the right audio output. This suggests there is a fundamental issue in the APU. Either registers aren't being loaded with the right values or internal handling of the logic isn't done right somewhere.

**Comment by maij** [comment] 2022-10-25 22:21
After doing some more testing in Sameboy I had a revelation. The key [line of code](https://github.com/LIJI32/SameBoy/blob/5d5ff1702e2bd3d48142e7069eb09adbb20ce520/Core/apu.c#L1047) that breaks certain types of audio output (e.g. voice samples, and the intro to Perfect Dark) is when the NR50 and NR51 registers are written to, the sample voltage of each channel is automatically reset to 0x10 (0b00010000). I believe this is simply the "zero volt" output level that comes from the real DAC on the DMG/GBC. 

If I simply change the channel suppression default value in the core to 0x10, all of these PCM audio samples appear fixed. Some more testing is needed, while most audio sounds correct to me, there is at least one issue: the power-on Gameboy ding has some ringing to it.

N.B. The issues #176 and #203 are resolved with this fix.

**Closed** 2022-11-06 13:07 UTC
Labels: bug
