### ISSUE TITLE
Feature Request: Real-Time Cock Support

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/Gameboy_MiSTer#131] opened 2021-01-18 12:08 UTC
Following on from a conversation on the Discord channel, it would be good to get the RTC functionality into the core.  The work was done in branch (however may no longer be compatible) but the work need to be done to save RTC bytes to the SD card.

The following games would benefit from the RTC:

Real-Time Clock: Games using the MBC3 mapper and a crystal oscillator to keep an accurate clock even with the game boy off.

Barcode Taisen Bardigun
Bokujo Monogatari GB / Harvest Moon GB
Cardcaptor Sakura - Itsumo Sakura-chan to Issho
E.T. - The Extra-Terrestrial - Digital Companion
The Great Battle Pocket
Itsudemo! Nyan to Wonderful
Kandzume Monsters
Keitai Denjuu Telefang - Power/Speed Version
Mary-Kate and Ashley - Pocket Planner
Nikkan Berutomo Club
Pokemon Gold/Silver/Crystal (All regions, all versions)
Tottoko Hamtaro - Tomodachi Daisakusen Dechu
Trade & Battle Card Hero

**Comment by SegaSnatcher** [comment] 2021-01-25 09:46
Have you tested the latest release with RTC support?

**Comment by brunolazzaro** [comment] 2021-01-25 21:44
I'm not OP, but I did try Pokemon Crystal and the clock did seem to go up during gameplay (whereas before it was stuck at the initial set time). I've yet to do more testing to see if the clock moves up while the system is off.

I believe FPGAzumSpass shared a test ROM on the forums (https://misterfpga.org/download/file.php?id=1466) so I'll try to run that too later in the night and test some of the other games too.

**Comment by brunolazzaro** [comment] 2021-02-03 07:31
OK, did some *very* light testing today.

**Test Rom by FPGAzumSpass**:
![2021020217433620](https://user-images.githubusercontent.com/689386/106712937-4e322480-65bf-11eb-88af-514c16bcfa31.png)

Somehow it failed, although the timer seems correct on the other one.

**Pokemon Silver**:
![2021020217523351](https://user-images.githubusercontent.com/689386/106712940-4ecabb00-65bf-11eb-8924-3f5de8ca6969.png)

Started at 5:45 and took this screenshot at 5:52 (turned off the system). So it seems to at least be working correctly in games?

I don't have the know-how to help regarding the timing checks above failing or why they are failing, but overall the feature seems to be working as intended.

**Comment by RobertPeip** [comment] 2021-02-10 15:53
I tested with Pokemon Crystal and it kept the time and autocounted up for several weeks now, so the feature works.

The timer rom tests cycle accurate counting and reset behavior. To have this work,
- the core needs to be cycle accurate (it currently is not 100%)
- core sync must be off, as it pauses the core from time to time
- there are very likely some cycles on the intial counter start/reset wrong

I will not work to get it like 100ns more accurate, as it all is only initial behavior, long time behavior is proven to be correct.

Personally i would close this, unless someone reports a problem with a game.

**Comment by paulb-nl** [comment] 2021-04-12 14:42
I noticed that the test always expects the time to increment a full second after writing to the seconds register so I made it reset the subseconds counter after a write to the seconds register and that fixed most of the failures. 

After also adding the 6000-7FFF latching and some other changes it now passes the test.

**Comment by RobertPeip** [comment] 2021-04-13 05:00
Great that you found the true reason for this!

**Comment by paulb-nl** [comment] 2021-11-08 12:25
This can be closed.

**Closed** 2021-11-08 17:06 UTC
